export enum School {
  FST = 'Faculté des Sciences et Techniques',
  FS = 'Faculté des Sciences',
  FG = 'Faculté des Sciences Juridiques, Economiques et Sociales',
  FSE = 'Faculté des Sciences Economiques',
  FSEG = 'Faculté des Sciences Economiques et de Gestion',
  FMP = 'Faculté de Médecine et de Pharmacie',
  ENF = 'Ecole Normale Supérieure',
  ENSA = 'Ecole Nationale des Sciences Appliquées',
  ENCG = 'Ecole Nationale de Commerce et de Gestion',
  ENSET = 'Ecole Normale Supérieure de l’Enseignement Technique',
  ENA = 'Ecole Nationale d’Agriculture',
  ENSAM = 'Ecole Nationale Supérieure d’Arts et Métiers',
  IUT = 'Institut Universitaire de Technologie',
  ISCAE = 'Institut Supérieur de Commerce et d’Administration des Entreprises',
  INSA = 'Institut National des Sciences Appliquées',
  ENSETFAR = 'Ecole Nationale Supérieure de l’Enseignement Technique (Far)',
  EHTP = 'Ecole Hassania des Travaux Publics',
  EMI = 'Ecole Mohammadia d’Ingénieurs',
  ENSIAS = 'Ecole Nationale Supérieure d’Informatique et d’Analyse des Systèmes',
  AUTRE = 'Autre',
}
